version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    environment:
      NODE_ENV: production
      PYTHON_EXECUTOR: python-executor
      JS_EXECUTOR: javascript-executor
      CPP_EXECUTOR: cpp-executor
    depends_on:
      - python-executor
      - javascript-executor
      - cpp-executor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/code-execution-temp:/tmp/code-execution-temp # <-- use real /tmp now
    user: "0:0"
    restart: unless-stopped

  python-executor:
    build:
      context: .
      dockerfile: Dockerfile.python
    stdin_open: true
    tty: true
    volumes:
      - /tmp/code-execution-temp:/app # <-- fix this too
    restart: unless-stopped

  javascript-executor:
    build:
      context: .
      dockerfile: Dockerfile.javascript
    stdin_open: true
    tty: true
    volumes:
      - /tmp/code-execution-temp:/app # <-- fix this too
    restart: unless-stopped

  cpp-executor:
    build:
      context: .
      dockerfile: Dockerfile.cpp
    volumes:
      - /tmp/code-execution-temp:/app # <-- fix this too
    restart: unless-stopped
